export default {
  products: [
    {
      _id: "1",
      name: "Logitech g29 wheel",
      category: "controller",
      image: "/images/p1.png",
      price: 28999,
      brand: "Logitech",
      rating: 4.5,
      numReviews: 678,
      countInStock: 4,
    },
    {
      _id: "2",
      name: "Playstation 4 controller",
      category: "controller",
      image: "/images/p2.png",
      price: 2499,
      brand: "SONY",
      rating: 4.2,
      numReviews: 245,
      countInStock: 6,
    },
    {
      _id: "3",
      name: "Logitech g305 lightspeed mouse",
      category: "accessories",
      image: "/images/p3.png",
      price: 2499,
      brand: "Logitech",
      rating: 4.6,
      numReviews: 867,
      countInStock: 7,
    },
    {
      _id: "4",
      name: "SOG headphones",
      category: "accessories",
      image: "/images/p4.png",
      price: 3000,
      brand: "SOG",
      rating: 4.1,
      numReviews: 124,
      countInStock: 5,
    },
    {
      _id: "5",
      name: "Xbox series S Console",
      category: "consoles",
      image: "/images/p5.png",
      price: 40999,
      brand: "XBOX",
      rating: 4.8,
      numReviews: 1324,
      countInStock: 0,
    },
    {
      _id: "6",
      name: "SONY Playstation 2",
      category: "consoles",
      image: "/images/p6.png",
      price: 28999,
      brand: "SONY",
      rating: 4.5,
      numReviews: 678,
      countInStock: 1,
    },
    {
      _id: "7",
      name: "AVERMedia capture card",
      category: "accessories",
      image: "/images/p7.png",
      price: 6099,
      brand: "avermedia",
      rating: 3.8,
      numReviews: 435,
      countInStock: 3,
    },
    {
      _id: "8",
      name: "Cougar headphones",
      category: "accessories",
      image: "/images/p8.png",
      price: 7899,
      brand: "cougar",
      rating: 4.5,
      numReviews: 1897,
      countInStock: 1,
    },
    {
      _id: "9",
      name: "Blue yeti snowball microphone",
      category: "accessories",
      image: "/images/p9.png",
      price: 14999,
      brand: "blue",
      rating: 4.8,
      numReviews: 766,
      countInStock: 5,
    },
    {
      _id: "10",
      name: "Aorus RX580 OC edition",
      category: "graphic cards",
      image: "/images/p10.png",
      price: 25799,
      brand: "aorus",
      rating: 4.4,
      numReviews: 695,
      countInStock: 0,
    },
  ],
};
